### PR TITLE
Update theme, author and title

### PR DESCRIPTION
**Pull request by ineczka**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
## Step 6: Create a blog post

:warning: Do not merge yet! :warning:

This pull request looks great so far. :sparkles: You've just edited the `_config.yml` file! As you work more with Jekyll, you'll see that the `_config.yml` file is very important and can hold a lot of information.

We have some more work to do to create your blog. You can continue to make commits on your `ineczka-patch-3` branch, and the pull request will update automatically.

### :keyboard: Activity: Add some content to your blog

1. On the "Code" tab, select your `ineczka-patch-3` branch
1. Click **Create new file**
1. Name the file `_posts/YYYY-MM-DD-title.md`, but replace the `YYYY-MM-DD` with today's date, and `title` with the title you'd like to use for your first blog post

   - [Jekyll is very particular about how you title blog posts.](https://jekyllrb.com/docs/posts/#creating-post-files) They must follow the convention shown above.

1. Type a quick draft of whatever you'd like to blog about. Remember, you can always edit it later
1. Scroll to the bottom and commit your changes to your branch

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ineczka — COMMENTED** [review]
On track

**Review by ghost — COMMENTED** [review]
## Step 7: Add blog post metadata

Your blog post is looking good - the naming can be tricky, but you got it right!

Just like the `_config.yml` file had some special syntax, files in Jekyll use some special syntax, too. This special syntax is called YAML front matter. It goes at the top of your file and looks something like this:

```yml
---
title: "Welcome to my blog"
date: 2019-01-20
---
```
This example will add a title and date to your blog post. There are other useful things you could add here in the future, like layouts, categories, or any other logic that is useful to you. [You can read more about that here](https://jekyllrb.com/docs/posts/).

### :keyboard: Activity: Add Front Matter

1. Click the "Files Changed" tab in this pull request
1. Click on the pencil icon on the right side of the screen
1. Add the following content to the top of your blog post:

       ---
       title: "YOUR-TITLE"
       date: YYYY-MM-DD
       ---

1. Replace YOUR-TITLE with a great title for your blog post
1. Replace YYYY-MM-DD with today's date
1. Commit your changes to your branch

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ghost — CHANGES_REQUESTED** [review]
## Checking your front matter

Front matter is tricky at first! Let's take a look at how you did:

- [ ] You used dashes on the first and final line
- [x] You added a page title surrounded in quotes
- [ ] You added a date using the correct format

Remember, your yaml front matter should be at the top of your blog post and it should look something like this:

```yaml
---
title: "Your blog post title"
date:  YYYY-MM-DD
---
```

### :keyboard: Activity: Edit your file

1. Click the "Files Changed" tab in this pull request
1. Click on the pencil icon on the right side of the screen
1. Make adjustments based on the above errors
1. Scroll to the bottom, and commit your changes

If you would like assistance troubleshooting the issue you are encountering, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learn/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ghost — CHANGES_REQUESTED** [review]
## Checking your front matter

Front matter is tricky at first! Let's take a look at how you did:

- [x] You used dashes on the first and final line
- [x] You added a page title surrounded in quotes
- [ ] You added a date using the correct format

Remember, your yaml front matter should be at the top of your blog post and it should look something like this:

```yaml
---
title: "Your blog post title"
date:  YYYY-MM-DD
---
```

### :keyboard: Activity: Edit your file

1. Click the "Files Changed" tab in this pull request
1. Click on the pencil icon on the right side of the screen
1. Make adjustments based on the above errors
1. Scroll to the bottom, and commit your changes

If you would like assistance troubleshooting the issue you are encountering, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learn/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ghost — CHANGES_REQUESTED** [review]
## Checking your front matter

Front matter is tricky at first! Let's take a look at how you did:

- [x] You used dashes on the first and final line
- [x] You added a page title surrounded in quotes
- [ ] You added a date using the correct format

Remember, your yaml front matter should be at the top of your blog post and it should look something like this:

```yaml
---
title: "Your blog post title"
date:  YYYY-MM-DD
---
```

### :keyboard: Activity: Edit your file

1. Click the "Files Changed" tab in this pull request
1. Click on the pencil icon on the right side of the screen
1. Make adjustments based on the above errors
1. Scroll to the bottom, and commit your changes

If you would like assistance troubleshooting the issue you are encountering, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learn/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ghost — CHANGES_REQUESTED** [review]
## Checking your front matter

Front matter is tricky at first! Let's take a look at how you did:

- [ ] You used dashes on the first and final line
- [x] You added a page title surrounded in quotes
- [ ] You added a date using the correct format

Remember, your yaml front matter should be at the top of your blog post and it should look something like this:

```yaml
---
title: "Your blog post title"
date:  YYYY-MM-DD
---
```

### :keyboard: Activity: Edit your file

1. Click the "Files Changed" tab in this pull request
1. Click on the pencil icon on the right side of the screen
1. Make adjustments based on the above errors
1. Scroll to the bottom, and commit your changes

If you would like assistance troubleshooting the issue you are encountering, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learn/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ghost — CHANGES_REQUESTED** [review]
## Checking your front matter

Front matter is tricky at first! Let's take a look at how you did:

- [ ] You used dashes on the first and final line
- [x] You added a page title surrounded in quotes
- [x] You added a date using the correct format

Remember, your yaml front matter should be at the top of your blog post and it should look something like this:

```yaml
---
title: "Your blog post title"
date:  YYYY-MM-DD
---
```

### :keyboard: Activity: Edit your file

1. Click the "Files Changed" tab in this pull request
1. Click on the pencil icon on the right side of the screen
1. Make adjustments based on the above errors
1. Scroll to the bottom, and commit your changes

If you would like assistance troubleshooting the issue you are encountering, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learn/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.

<hr>
<h3 align="center">Watch below for my response</h3>

**Review by ghost — APPROVED** [review]
## Step 8: Merge your first post

Nice work @ineczka :tada: Users will be reading your blog in no time!

### :keyboard: Activity: Merge your pull request

1. If satisfied with your post, click **Merge pull request**
1. Click **Confirm merge**
1. Click **Delete branch**

<hr>
<h3 align="center">Watch below for my response</h3>

**Pull request merged**
